name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build

    - name: Deploy to Azure VM
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az vm run-command invoke -g myResourceGroup -n myVM --command-id RunShellScript --scripts "cd /var/www/html && git pull https://github.com/YOUR_USERNAME/gcp-devops-assignment.git && npm install && npm run start"
